@UltimateFlags_Api_v10_HostAddress = https://localhost:7022

GET {{UltimateFlags_Api_v10_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{UltimateFlags_Api_v10_HostAddress}}/health-check/
Accept: application/json

###
