@UltimateFlags_Api_v8_HostAddress = https://localhost:7233

GET {{UltimateFlags_Api_v8_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{UltimateFlags_Api_v8_HostAddress}}/health-check/
Accept: application/json

###
